server:
  port: 10000

spring:
  application:
    name: msa-api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE

      routes:
        - id: msa-user-api
          uri: lb://MSA-USER-SERVICE
          predicates:
            - Path=/api/users/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/api/users/(?<segment>.*), /$\{segment}
        - id: msa-survey-api
          uri: lb://MSA-SURVEY-SERVICE
          predicates:
            - Path=/api/surveys/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/api/surveys/(?<segment>.*), /$\{segment}
        - id: msa-survey-api
          uri: lb://MSA-SURVEY-SERVICE
          predicates:
            - Path=/api/questions/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/api/questions/(?<segment>.*), /$\{segment}
        - id: msa-survey-api
          uri: lb://MSA-SURVEY-SERVICE
          predicates:
            - Path=/api/answers/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/api/answers/(?<segment>.*), /$\{segment}
        - id: msa-survey-api
          uri: lb://MSA-SURVEY-SERVICE
          predicates:
            - Path=/api/examples/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/api/examples/(?<segment>.*), /$\{segment}
        - id: msa-auth-api
          uri: lb://MSA-AUTH-SERVICE
          predicates:
            - Path=/oauth/token/**
        - id: msa-auth-api
          uri: lb://MSA-AUTH-SERVICE
          predicates:
            - Path=/validateUser/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhostdis:8761/eureka/ # 같은 인스턴스
#      defaultZone: http://52.78.35.130:8761/eureka/ # 다른 인스턴스

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true # default: true
